language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
script:
<<<<<<< HEAD
  - python setup.py test
notifications:
  email: 
    - fiveholiday55@hotmail.com
=======
   - python setup.py test
>>>>>>> 70cfc422323cf04efdd58d098a5ebe086b316a6a
